### ISSUE TITLE
"Save the residuals"

### ISSUE THREAD

**Issue by kaseympotts** [Watts-College/cpp-523-fall-2021#7]
I'm a total R n00b, so bear with me. What does it mean by "save the residuals?" I can write this stuff out long hand on pen and paper and do the math, but I'm stuck with the code.

Last week I was able to push buttons and play around until I figured the assignment out. This week, not so much. 
Am I overlooking something glaringly obvious?

Hoping that a small hint will help me get moving again on this one.

**Comment by ebossert** [comment]
I reviewed some old issues from previous classes and I don't believe we are expected to change the code, if that's what you're asking. I could be totally wrong though.
https://github.com/DS4PS/cpp-523-sum-2020/issues/11

I think that "saving the residuals" is what happens when running the residuals scatterplot after the linear regression model. Or it could be saving it in the environment since the residuals for model 1 appear when you click on "m1."

**Comment by kaseympotts** [comment]
Thanks! - facepalm- after sleeping on it, and now reading your reply, I was DEFINITELY missing the obvious. I'm getting reminded why I struggle without an in-class lecture, but I'm determined to keep this struggle bus moving forward.

Thanks again!
